name: Deploy a Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Desplegando a Surge
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar a Surge
        run: surge ./ primer-parcial-keylin-rosario.surge.sh --token ${{ secrets.SURGE_TOKEN }}